title: Data Analysis Portfolio by Ian Tavarez
description: Welcome to my data analysis portfolio. Here you will find a collection of my data analysis projects showcasing my skills and expertise.
theme: jekyll-theme-cayman
